[project]
name = "travel-data"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "asyncmy>=0.2.11",
    "fastapi>=0.115.0",
    "httpx>=0.28.1",
    "loguru>=0.7.3",
    "pytest>=9.0.0",
    "pydantic>=2.12.5",
    "python-dotenv>=1.1.1",
    "pymysql>=1.1.2",
    "sqlacodegen>=4.0.3",
    "sqlalchemy>=2.0.49",
    "rich>=14.2.0",
    "uvicorn>=0.34.0",
    "tzdata",
]
